### ISSUE TITLE
Please submit issues at cjheath/treetop, not here.

### ISSUE THREAD

**Issue by cjheath** [nathansobo/treetop#38]
Treetop is not released from this repository, and issues may not be acknowledged. Please submit them to my repository instead.

**Comment by killthekitten** [comment]
Why not to mention it in `Readme`?

**Comment by cjheath** [comment]
Done.

**Comment by killthekitten** [comment]
@cjheath can't see any changes

**Comment by cjheath** [comment]
It's only in the github version so far. I'm not going to re-release a gem for a one-line Readme change.
