### ISSUE TITLE
Feature request: better module support in the .treetop file

### ISSUE THREAD

**Issue by jeff-hired** [nathansobo/treetop#41]
Instead of:

```
grammar QueryGrammar
  rule attribute
    [a-zA-Z0-9_.]+ <Search::Parser::QueryGrammar::Attribute>
  end
end
```

It'd be nice if I could write:

```
grammar Search::Parser::QueryGrammar
  rule attribute
    [a-zA-Z0-9_.]+ <Attribute>
  end
end
```

Apologies if there is a way to do this, but just adding the colons in the grammar name gave me an error: `RuntimeError: Expected one of [A-Za-z_], [0-9], [ \t\n\r], '#' at line 1, column 15 (byte 15) after grammar Search`

**Comment by cjheath** [comment]
You can wrap your grammar in nested modules:

    module Search
      module Parser
        grammar QueryGrammar
          ...
        end
      end
    end
