### ISSUE TITLE
Release note for 1.6.8

### ISSUE THREAD

**Issue by lucasmoura** [nathansobo/treetop#44]
Hello, I am currently considering updating the treetop version I am using, which is 1.6.3, to the new version of the project. However, I could not find any release note about the most recent version. Is there a place where I can read it ?

Also, if that place does exist, maybe that file should also be placed on the project root directory as well.

**Comment by cjheath** [comment]
No, release notes are not maintained. All the history is in the git log. Since 1.6.3 there have been only minor bug fixes.
